server:
port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo_with_image
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

    servlet:
    multipart:
    max-file-size: 64MB
    max-request-size: 64MB

    data:
        sql:
            init-mode: always
            mode: always

    jpa:
        hibernate:
        ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
        
        application:
            name: demo
        
    security:
        user:
            name: user
            password: password

    image:
    upload-dir: "C:/Users/Família Enéas/Desktop/demo/src/main/resources/static/images"